# Generated by Django 5.1 on 2024-08-22 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reports",
                to="myapp.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reports",
            unique_together={("milan", "user", "created_at", "common_user")},
        ),
        migrations.AddConstraint(
            model_name="reports",
            constraint=models.UniqueConstraint(
                fields=("milan", "user", "common_user", "created_at"),
                name="unique_report",
            ),
        ),
    ]
